### ISSUE TITLE
Error performing TLS handshake when publishing artifacts

### ISSUE THREAD

**Issue by mikhirev** [jenkinsci/publish-over-ftp-plugin#117]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.462.3
OS: Linux - 6.1.0-26-amd64
Java: 17.0.12 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
Parameterized-Remote-Trigger:3.2.0
analysis-model-api:12.9.0
android-emulator:592.vb_b_6d427f1923
ant:511.v0a_a_1a_334f41b_
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
apache-httpcomponents-client-5-api:5.4-118.v199115451c4d
asm-api:9.7.1-97.v4cc844130d97
authentication-tokens:1.119.v50285141b_7e1
authorize-project:1.7.2
bootstrap5-api:5.3.3-1
bouncycastle-api:2.30.1.78.1-248.ve27176eb_46cb_
branch-api:2.1178.v969d9eb_c728e
build-timeout:1.33
build-user-vars-plugin:176.vb_9c7907fd524
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.2.1
clang-scanbuild:1.8
cloud-stats:336.v788e4055508b_
cloudbees-folder:6.955.v81e2a_35c08d3
command-launcher:115.vd8b_301cc15d0
commons-compress-api:1.26.1-2
commons-lang3-api:3.17.0-84.vb_b_938040b_078
commons-text-api:1.12.0-129.v99a_50df237f7
conditional-buildstep:1.4.3
config-file-provider:978.v8e85886ffdc4
configuration-as-code:1850.va_a_8c31d3158b_
copyartifact:749.vfb_dca_a_9b_6549
credentials:1384.vf0a_2ed06f9c6
credentials-binding:681.vf91669a_32e45
cvs:2.19.1
data-tables-api:2.1.8-1
date-parameter:0.0.4
debian-pbuilder:1.11
display-url-api:2.204.vf6fddd8a_8b_e9
docker-commons:443.v921729d5611d
docker-java-api:3.4.0-94.v65ced49b_a_7d5
docker-plugin:1.7.0
docker-workflow:580.vc0c340686b_54
durable-task:577.v2a_8a_4b_7c0247
echarts-api:5.5.1-1
eddsa-api:0.3.0-4.v84c6f0f4969e
email-ext:1844.v3ea_a_b_842374a_
emailext-template:1.5
envinject:2.919.v009a_a_1067cd0
envinject-api:1.199.v3ce31253ed13
environment-script:100.v3a_f1a_6a_b_7549
extended-choice-parameter:382.v5697b_32134e8
extended-read-permission:53.v6499940139e5
external-monitor-job:215.v2e88e894db_f8
font-awesome-api:6.6.0-2
forensics-api:2.6.0
git:5.5.2
git-client:5.0.0
git-parameter:0.9.19
git-server:126.v0d945d8d2b_39
git-tag-message:1.7.1
gitlab-api:5.6.0-97.v6603a_83f8690
gitlab-branch-source:711.v41fb_c8b_2b_7a_e
gitlab-plugin:1.8.2
groovy-label-assignment:1.2.0
gson-api:2.11.0-85.v1f4e87273c33
handy-uri-templates-2-api:2.1.8-30.v7e777411b_148
htmlpublisher:1.36
instance-identity:201.vd2a_b_5a_468a_a_6
ionicons-api:74.v93d5eb_813d5f
ivy:2.6
jackson2-api:2.17.0-379.v02de8ec9f64c
jakarta-activation-api:2.1.3-1
jakarta-mail-api:2.1.3-1
javadoc:280.v050b_5c849f69
javax-activation-api:1.2.0-7
javax-mail-api:1.6.2-10
jaxb:2.3.9-1
jdk-tool:80.v8a_dee33ed6f0
jersey2-api:2.44-151.v6df377fff741
jnr-posix-api:3.1.19-2
jobConfigHistory:1277.vb_9a_0808495d7
joda-time-api:2.13.0-93.v9934da_29b_a_e9
jquery:1.12.4-1
jquery3-api:3.7.1-2
jsch:0.2.16-86.v42e010d9484b_
json-api:20240303-101.v7a_8666713110
json-path-api:2.9.0-118.v7f23ed82a_8b_8
junit:1304.vc85a_b_ca_96613
kpp-management-plugin:105.v767485951b_d2
ldap:725.v3cb_b_711b_1a_ef
lockable-resources:1315.v4ea_8e5159ec8
mailer:488.v0c9639c1a_eb_3
mantis:0.26
mapdb-api:1.0.9-40.v58107308b_7a_7
matrix-auth:3.2.2
matrix-project:839.vff91cd7e3a_b_2
maven-plugin:3.23
mina-sshd-api-common:2.14.0-133.vcc091215a_358
mina-sshd-api-core:2.14.0-133.vcc091215a_358
multi-branch-project-plugin:0.7
multiple-scms:0.8
nodelabelparameter:1.12.0
pam-auth:1.11
parameterized-trigger:806.vf6fff3e28c3e
pipeline-build-step:540.vb_e8849e1a_b_d8
pipeline-graph-analysis:216.vfd8b_ece330ca_
pipeline-groovy-lib:730.ve57b_34648c63
pipeline-input-step:495.ve9c153f6067b_
pipeline-milestone-step:119.vdfdc43fc3b_9a_
pipeline-model-api:2.2214.vb_b_34b_2ea_9b_83
pipeline-model-definition:2.2214.vb_b_34b_2ea_9b_83
pipeline-model-extensions:2.2214.vb_b_34b_2ea_9b_83
pipeline-rest-api:2.34
pipeline-stage-step:312.v8cd10304c27a_
pipeline-stage-tags-metadata:2.2214.vb_b_34b_2ea_9b_83
pipeline-stage-view:2.34
pipeline-utility-steps:2.18.0
plain-credentials:183.va_de8f1dd5a_2b_
plugin-util-api:5.1.0
port-allocator:1.10
pragprog:2.0.0
prism-api:1.29.0-17
promoted-builds:965.vcda_c6a_e0998f
publish-over:0.22
publish-over-ftp:1.17
publish-over-ssh:1.25
rebuild:332.va_1ee476d8f6d
resource-disposer:0.24
rocketchatnotifier:1.5.2
role-strategy:743.v142ea_b_d5f1d3
run-condition:1.7
saml:4.464.vea_cb_75d7f5e0
scm-api:696.v778d637b_a_762
script-security:1362.v67dc1f0e1b_b_3
secondary-timestamper-plugin:1.1
snakeyaml-api:2.3-123.v13484c65210a_
ssh-agent:376.v8933585c69d3
ssh-credentials:343.v884f71d78167
ssh-slaves:2.973.v0fa_8c0dea_f9f
sshd:3.330.vc866a_8389b_58
started-by-envvar:1.0
structs:338.v848422169819
subversion:1275.va_7b_014f3fc2c
text-file-operations:1.3.2
throttle-concurrents:2.14
timestamper:1.27
token-macro:400.v35420b_922dcb_
trilead-api:2.147.vb_73cc728a_32e
variant:60.v7290fc0eb_b_cd
versionnumber:1.11
violation-comments-to-gitlab:2.62.0
warnings-ng:11.9.0
workflow-aggregator:600.vb_57cdd26fdd7
workflow-api:1336.vee415d95c521
workflow-basic-steps:1058.vcb_fc1e3a_21a_9
workflow-cps:3975.v567e2a_1ffa_22
workflow-durable-task-step:1371.vb_7cec8f3b_95e
workflow-job:1436.vfa_244484591f
workflow-multibranch:795.ve0cb_1f45ca_9a_
workflow-scm-step:427.v4ca_6512e7df1
workflow-step-api:678.v3ee58b_469476
workflow-support:926.v9f4f9b_b_98c19
ws-cleanup:0.47
xcode-plugin:2.0.17-565.v1c48051d46ef
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Alpine Linux.

### Reproduction steps

1. Configure FTP server with "Use FTP over TLS" checkbox enabled.
2. Ensure that test connection is successful.
3. Create a job, add a "Send build artifacts over FTP" post-build step ans select a server configured above.
4. Run job.

### Expected Results

Artifacts are published on FTP server.

### Actual Results

Unlike test connection, an error occurs after `AUTH TLS` command:

```
ERROR: Exception when publishing, exception message [Failed to connect and initialize FTP connection. Message: [javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty]]
```

### Anything else?

<details>
<summary>from system log</summary>

```
WARNING: Exception when publishing, exception message [Failed to connect and initialize FTP connection. Message: [javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty]]
jenkins.plugins.publish_over.BapPublisherException: Failed to connect and initialize FTP connection. Message: [javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty]
	at PluginClassLoader for publish-over-ftp//jenkins.plugins.publish_over_ftp.BapFtpHostConfiguration.createClient(BapFtpHostConfiguration.java:145)
	at PluginClassLoader for publish-over-ftp//jenkins.plugins.publish_over_ftp.BapFtpHostConfiguration.createClient(BapFtpHostConfiguration.java:61)
	at PluginClassLoader for publish-over//jenkins.plugins.publish_over.BPHostConfiguration.createClient(BPHostConfiguration.java:96)
	at PluginClassLoader for publish-over//jenkins.plugins.publish_over.BapPublisher$Performer.perform(BapPublisher.java:229)
	at PluginClassLoader for publish-over//jenkins.plugins.publish_over.BapPublisher$Performer.access$000(BapPublisher.java:205)
	at PluginClassLoader for publish-over//jenkins.plugins.publish_over.BapPublisher.perform(BapPublisher.java:158)
	at PluginClassLoader for publish-over//jenkins.plugins.publish_over.BPCallablePublisher.invoke(BPCallablePublisher.java:65)
	at PluginClassLoader for publish-over//jenkins.plugins.publish_over.BPCallablePublisher.invoke(BPCallablePublisher.java:38)
	at Jenkins v2.462.3//hudson.FilePath$FileCallableWrapper.call(FilePath.java:3615)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:377)
	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:352)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:295)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:290)
	at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1684)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:466)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:422)
	at PluginClassLoader for publish-over-ftp//org.apache.commons.net.ftp.FTPSClient.sslNegotiation(FTPSClient.java:283)
	at PluginClassLoader for publish-over-ftp//org.apache.commons.net.ftp.FTPSClient._connectAction_(FTPSClient.java:225)
	at PluginClassLoader for publish-over-ftp//org.apache.commons.net.SocketClient._connect(SocketClient.java:254)
	at PluginClassLoader for publish-over-ftp//org.apache.commons.net.SocketClient.connect(SocketClient.java:212)
	at PluginClassLoader for publish-over-ftp//jenkins.plugins.publish_over_ftp.BapFtpHostConfiguration.connect(BapFtpHostConfiguration.java:246)
	at PluginClassLoader for publish-over-ftp//jenkins.plugins.publish_over_ftp.BapFtpHostConfiguration.init(BapFtpHostConfiguration.java:194)
	at PluginClassLoader for publish-over-ftp//jenkins.plugins.publish_over_ftp.BapFtpHostConfiguration.createClient(BapFtpHostConfiguration.java:143)
	... 16 more
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:102)
	at java.base/sun.security.validator.Validator.getInstance(Validator.java:181)
	at java.base/sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:300)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:176)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:189)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1501)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1411)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:451)
	... 24 more
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.base/java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
	at java.base/java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
	at java.base/java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
	at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:99)
	... 40 more

Nov 01, 2024 11:28:54 AM WARNING jenkins.plugins.publish_over.BPInstanceConfig perform

An exception was caught when invoking perform
java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.base/java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
	at java.base/java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
	at java.base/java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
	at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:99)
Caused: java.lang.RuntimeException: Unexpected error
	at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:102)
	at java.base/sun.security.validator.Validator.getInstance(Validator.java:181)
	at java.base/sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:300)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:176)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:189)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1501)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1411)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:451)
Caused: javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:352)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:295)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:290)
	at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1684)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:466)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:422)
	at PluginClassLoader for publish-over-ftp//org.apache.commons.net.ftp.FTPSClient.sslNegotiation(FTPSClient.java:283)
	at PluginClassLoader for publish-over-ftp//org.apache.commons.net.ftp.FTPSClient._connectAction_(FTPSClient.java:225)
	at PluginClassLoader for publish-over-ftp//org.apache.commons.net.SocketClient._connect(SocketClient.java:254)
	at PluginClassLoader for publish-over-ftp//org.apache.commons.net.SocketClient.connect(SocketClient.java:212)
	at PluginClassLoader for publish-over-ftp//jenkins.plugins.publish_over_ftp.BapFtpHostConfiguration.connect(BapFtpHostConfiguration.java:246)
	at PluginClassLoader for publish-over-ftp//jenkins.plugins.publish_over_ftp.BapFtpHostConfiguration.init(BapFtpHostConfiguration.java:194)
	at PluginClassLoader for publish-over-ftp//jenkins.plugins.publish_over_ftp.BapFtpHostConfiguration.createClient(BapFtpHostConfiguration.java:143)
Caused: jenkins.plugins.publish_over.BapPublisherException: Failed to connect and initialize FTP connection. Message: [javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty]
	at PluginClassLoader for publish-over-ftp//jenkins.plugins.publish_over_ftp.BapFtpHostConfiguration.createClient(BapFtpHostConfiguration.java:145)
	at PluginClassLoader for publish-over-ftp//jenkins.plugins.publish_over_ftp.BapFtpHostConfiguration.createClient(BapFtpHostConfiguration.java:61)
	at PluginClassLoader for publish-over//jenkins.plugins.publish_over.BPHostConfiguration.createClient(BPHostConfiguration.java:96)
	at PluginClassLoader for publish-over//jenkins.plugins.publish_over.BapPublisher$Performer.perform(BapPublisher.java:229)
	at PluginClassLoader for publish-over//jenkins.plugins.publish_over.BapPublisher$Performer.access$000(BapPublisher.java:205)
	at PluginClassLoader for publish-over//jenkins.plugins.publish_over.BapPublisher.perform(BapPublisher.java:158)
	at PluginClassLoader for publish-over//jenkins.plugins.publish_over.BPCallablePublisher.invoke(BPCallablePublisher.java:65)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to livedisk-builder-xenial-000mewmlh3n02
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1826)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1042)
		at hudson.FilePath.act(FilePath.java:1229)
		at hudson.FilePath.act(FilePath.java:1218)
		at PluginClassLoader for publish-over//jenkins.plugins.publish_over.BPInstanceConfig.perform(BPInstanceConfig.java:141)
		at PluginClassLoader for publish-over//jenkins.plugins.publish_over.BPPlugin.perform(BPPlugin.java:126)
		at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
		at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:80)
		at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
		at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:818)
		at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:767)
		at hudson.model.Build$BuildExecution.post2(Build.java:179)
		at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:711)
		at hudson.model.Run.execute(Run.java:1917)
		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
		at hudson.model.ResourceController.execute(ResourceController.java:101)
		at hudson.model.Executor.run(Executor.java:446)
Caused: jenkins.plugins.publish_over.BapPublisherException: Exception when publishing, exception message [Failed to connect and initialize FTP connection. Message: [javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty]]
	at PluginClassLoader for publish-over//jenkins.plugins.publish_over.BPCallablePublisher.invoke(BPCallablePublisher.java:69)
	at PluginClassLoader for publish-over//jenkins.plugins.publish_over.BPCallablePublisher.invoke(BPCallablePublisher.java:38)
	at Jenkins v2.462.3//hudson.FilePath$FileCallableWrapper.call(FilePath.java:3615)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:377)
	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
</details>

**Comment by yuvpg** [comment]
Most probably Trust Store location is not configured for running instances of java. Try to specify location of `cacerts` file explicitly in `jenkins.xml` and node invocation scripts by adding parameter to java exectuable:
```
  <executable>C:\Program Files\Java\jdk-21\bin\java.exe</executable>
  <arguments>-Djavax.net.ssl.trustStore="C:/Program Files/Java/jdk-21/lib/security/cacerts" -Djavax.net.ssl.trustStorePassword=changeit  [...]</arguments>
```

```
java -Djavax.net.ssl.trustStore="C:/Program Files/Java/jdk-21/lib/security/cacerts" -Djavax.net.ssl.trustStorePassword=changeit -jar agent.jar [...]
```

**Comment by cubistico** [comment]
I disagree with @yuvpg, because the trust store is definitely available to the Java instance. Configuring the same connection with _Use Implicit TLS_ works, while _Use FTP Over TLS_ fails.

The problem occurs after AUTH TLS:

````
FTP: Connecting from host [originating-host]
FTP: Connecting with configuration [upload-target-host] ...
220 FTP on dd57514.kasserver.com ready
AUTH TLS
234 AUTH TLS successful
ERROR: Exception when publishing, exception message [Failed to connect and initialize FTP connection. Message: [javax.net.ssl.SSLException: (internal_error) Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty]]
````
It seems very easy to reproduce. In my case, artifacts were published from a Jenkins node.
