### ISSUE TITLE
[JENKINS-63214] Could not write file: 522 SSL/TLS required (...)

### ISSUE THREAD

**Issue by jira-importer** [jenkinsci/publish-over-ftp-plugin#71]
<p>After configuring the <em>publish-over-ftp-plugin</em> properly (Configuration test is successful) the plugin is not able to transfer the artifacts.</p>

<p>The directories are being created properly put not the artifacts.</p>

<p>Exception stack:</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>2020-07-26 19:11:20.369+0000 [id=595]   WARNING j.p.p.BPInstanceConfig#perform: An exception was caught when invoking perform
jenkins.plugins.publish_over.BapPublisherException: Could not write file. Server message: [522 SSL/TLS required on the data channel
]
at jenkins.plugins.publish_over_ftp.BapFtpClient.transferFile(BapFtpClient.java:139)
at jenkins.plugins.publish_over_ftp.BapFtpClient.transferFile(BapFtpClient.java:40)
at jenkins.plugins.publish_over.BPTransfer.transferFile(BPTransfer.java:171)
at jenkins.plugins.publish_over.BPTransfer.transfer(BPTransfer.java:155)
at jenkins.plugins.publish_over.BPTransfer.transfer(BPTransfer.java:142)
at jenkins.plugins.publish_over.BapPublisher$Performer.transfer(BapPublisher.java:276)
at jenkins.plugins.publish_over.BapPublisher$Performer.perform(BapPublisher.java:232)
at jenkins.plugins.publish_over.BapPublisher$Performer.access$000(BapPublisher.java:205)
at jenkins.plugins.publish_over.BapPublisher.perform(BapPublisher.java:158)
at jenkins.plugins.publish_over.BPCallablePublisher.invoke(BPCallablePublisher.java:65)
Caused: jenkins.plugins.publish_over.BapPublisherException: Exception when publishing, exception message [Could not write file. Server message: [522 SSL/TLS required on the data channel
]]
at jenkins.plugins.publish_over.BPCallablePublisher.invoke(BPCallablePublisher.java:69)
at jenkins.plugins.publish_over.BPCallablePublisher.invoke(BPCallablePublisher.java:38)
at hudson.FilePath.act(FilePath.java:1075)
at hudson.FilePath.act(FilePath.java:1058)
at jenkins.plugins.publish_over.BPInstanceConfig.perform(BPInstanceConfig.java:141)
at jenkins.plugins.publish_over.BPPlugin.perform(BPPlugin.java:126)
at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
at hudson.model.Build$BuildExecution.post2(Build.java:186)
at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
at hudson.model.Run.execute(Run.java:1905)
at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
at hudson.model.ResourceController.execute(ResourceController.java:97)
at hudson.model.Executor.run(Executor.java:428)
getConfigPage -> /ci_skip_wrapper/config</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Joel Strasser" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=joestr">joestr</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-63214" target="_blank">Could not write file: 522 SSL/TLS required (...)</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by sberer** [comment]
Any feedback on this? I have the same issue.

**Comment by Yuriy11** [comment]
Same issue, test connection reports success, directories are created but files are not uploaded.

**Comment by derhecht** [comment]
same issue in 1.17

**Comment by Saidhoussem** [comment]
hi,
Any feedback on this? I have the same issue.

**Comment by sephiroth-j** [comment]
The error is caused by the lack of support for TLS session reuse in [Apache Commons Net](https://commons.apache.org/proper/commons-net/) – see [NET-408](https://issues.apache.org/jira/browse/NET-408).

**Comment by yuvpg** [comment]
For vsftpd this combination of settings resolves the issue:
```
force_local_logins_ssl=YES
force_local_data_ssl=NO
require_ssl_reuse=NO
```
But this effectively disables encryption of data transfers (only login information is encrypted)

**Comment by yuvpg** [comment]
See also PR "Data channel protection support for explicit TLS" https://github.com/jenkinsci/publish-over-ftp-plugin/pull/24
